/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteJjArgs } from "./DeleteJjArgs";
import { JjCountArgs } from "./JjCountArgs";
import { JjFindManyArgs } from "./JjFindManyArgs";
import { JjFindUniqueArgs } from "./JjFindUniqueArgs";
import { Jj } from "./Jj";
import { JjService } from "../jj.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Jj)
export class JjResolverBase {
  constructor(
    protected readonly service: JjService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Jj",
    action: "read",
    possession: "any",
  })
  async _jjsMeta(@graphql.Args() args: JjCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Jj])
  @nestAccessControl.UseRoles({
    resource: "Jj",
    action: "read",
    possession: "any",
  })
  async jjs(@graphql.Args() args: JjFindManyArgs): Promise<Jj[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Jj, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Jj",
    action: "read",
    possession: "own",
  })
  async jj(@graphql.Args() args: JjFindUniqueArgs): Promise<Jj | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Jj)
  @nestAccessControl.UseRoles({
    resource: "Jj",
    action: "delete",
    possession: "any",
  })
  async deleteJj(@graphql.Args() args: DeleteJjArgs): Promise<Jj | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
